### ISSUE TITLE
Move canvas in read-only mod

### ISSUE THREAD

**Issue by Kerblif** [cracker0dks/whiteboard#189]
Good afternoon.

I think it's a big omission that you can't move the board in read-only mod.

**Comment by cracker0dks** [comment]
true! I fixed that. Please give it a try.

**Comment by Kerblif** [comment]
Nope, something strange happened 

<img width="1428" alt="Screenshot 2024-05-06 at 2 05 23 PM" src="https://github.com/cracker0dks/whiteboard/assets/44944577/58274fd5-7327-49d6-bcf5-f54d47b2f472">

**Comment by cracker0dks** [comment]
Are you sure you are on the latest commit. Because we dont use require anymore.
Line 18 looks like this: https://github.com/cracker0dks/whiteboard/blob/master/scripts/server-backend.js#L18
So please try to checkout the latest master commit.

**Comment by Kerblif** [comment]
<img width="1437" alt="Screenshot 2024-05-07 at 12 16 44 PM" src="https://github.com/cracker0dks/whiteboard/assets/44944577/1767276a-944e-4dc9-b7dd-957463589878">

Yes, I'm sorry, I forgot. I took the new version, but an error still occurs

**Comment by cracker0dks** [comment]
ah, my bad. please pull and try again.

**Comment by Kerblif** [comment]
Thanks, everything is working!
